### ISSUE TITLE
It shows ALOT of errors

### ISSUE THREAD

**Issue by matejsworkshop** [m5stack/M5Core2_Weather_Dashboard#2]
Hello, this project is interesting, but it thrown out **alot** of errors. This may be because it was last updated so long ago. Is there any possible way that you can make a new version? Thanks.

**Comment by matejsworkshop** [comment]
Figured it out, downloaded ESP-IDF version 4.3.1.

**Comment by TinyuZhao** [comment]
OK, thank you for your feedback, I will indicate the IDF version in the README.
